/**
 * Generate JSON Schema from Zod schema for xling.json
 */
import * as z from "zod";
import { writeFileSync } from "node:fs";
import { XlingConfigSchema } from "../src/domain/xling/config.ts";

const jsonSchema = z.toJSONSchema(XlingConfigSchema, {
  target: "draft-7",
}) as Record<string, unknown>;

/**
 * Remove fields with defaults from required arrays recursively
 */
function fixOptionalFields(obj: unknown): void {
  if (!obj || typeof obj !== "object") return;

  const schema = obj as Record<string, unknown>;

  // If this object has properties and required, filter required based on defaults
  if (schema.properties && Array.isArray(schema.required)) {
    const props = schema.properties as Record<string, Record<string, unknown>>;
    schema.required = schema.required.filter((field) => {
      const prop = props[field as string];
      return prop && !("default" in prop);
    });
    if ((schema.required as string[]).length === 0) {
      delete schema.required;
    }
  }

  // Recurse into properties
  if (schema.properties) {
    for (const prop of Object.values(
      schema.properties as Record<string, unknown>,
    )) {
      fixOptionalFields(prop);
    }
  }

  // Recurse into items (arrays)
  if (schema.items) {
    fixOptionalFields(schema.items);
  }

  // Recurse into additionalProperties
  if (
    schema.additionalProperties &&
    typeof schema.additionalProperties === "object"
  ) {
    fixOptionalFields(schema.additionalProperties);
  }

  // Recurse into shared definitions/$defs generated by zod-to-json-schema
  for (const defsKey of ["definitions", "$defs"]) {
    const defs = schema[defsKey];
    if (defs && typeof defs === "object") {
      for (const value of Object.values(defs as Record<string, unknown>)) {
        fixOptionalFields(value);
      }
    }
  }

  // Recurse into anyOf/oneOf/allOf
  for (const key of ["anyOf", "oneOf", "allOf"]) {
    if (Array.isArray(schema[key])) {
      for (const item of schema[key] as unknown[]) {
        fixOptionalFields(item);
      }
    }
  }
}

fixOptionalFields(jsonSchema);

const schema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "Xling Configuration",
  description: "Configuration file for xling CLI tool",
  ...jsonSchema,
};

writeFileSync(
  "schemas/xling.schema.json",
  JSON.stringify(schema, null, 2) + "\n",
);

console.info("Generated schemas/xling.schema.json");
